### ISSUE TITLE
Give ISBN a default value or make nullable.

### ISSUE THREAD

**Issue by raynelfss** [ShehabMohsen/get-bookd#17]
Django is currently giving me a warning when making migrations:

```sh
It is impossible to add a non-nullable field 'isbn' to book without specifying a default. This is because the database needs something to populate existing rows.
Please select a fix:
 1) Provide a one-off default now (will be set on all existing rows with a null value for this column)
 2) Quit and manually define a default value in models.py
```
Two workarounds for these would be adding a default ISBN or making ISBN nullable for extreme cases.

**Comment by jedrm** [comment]
To fix and work around this in the future, you can delete the untracked files in the `migrations` folders in the server directory and delete `db.sqlite3`. You can run `makemigrations` and `migrate` again and there shouldn't be any issues anymore.

**Comment by raynelfss** [comment]
I'm getting the following issue when migrating:

```sh
django.db.utils.OperationalError: foreign key mismatch - "books_collection_books" referencing "books_collection"
```

**Comment by jedrm** [comment]
I just followed the steps that I gave and got no issues. Did you pull from `main`?

**Comment by raynelfss** [comment]
I did sir. Dunno what's wrong then. I'll try with recreating the environment from scratch.
